SELECT * FROM customers_behavior;
--Q1. What is the total revenue generated by male vs.female customers?
SELECT gender, sum(purchase_amount)
FROM customers_behavior
GROUP BY gender; 
-- Female revenue: 75191
-- Male revenue: 157890 

--Q2. Which customers used a discount but still spent more than average purchase amount.

SELECT customer_id, purchase_amount
FROM customers_behavior
WHERE discount_applied='Yes' AND purchase_amount>(SELECT ROUND(avg(purchase_amount), 2)
FROM customers_behavior);
-- There are 839 customers who spend more than average.

--Q3. Which are the top 5 products with the highest average review rating?
ALTER TABLE customers_behavior
ALTER COLUMN review_rating TYPE NUMERIC(5, 2);

SELECT item_purchased, ROUND(avg(review_rating),2) AS avg_rating
FROM customers_behavior
GROUP BY item_purchased
ORDER BY ROUND(avg(review_rating),2) DESC
LIMIT 5;
-- Gloves, Sandals, Boots, Hat and Shirt are the top products with average highest rating.

--Q4. Compare the average purchase amounts between standard and expression shipping.
SELECT shipping_type, ROUND(avg(purchase_amount),2) AS avg_purchase_amount
FROM customers_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
-- The average purchase amount for Standard shipping is 58.46 while 60.48 is for Express.



--Q5. Do subscribed customers spend more? Compare average spend and total revenue between
--subscribers and non-subscribers.
SELECT subscription_status, count(customer_id) AS total_customers, 
	ROUND(avg(purchase_amount), 2) AS avg_spending, ROUND(sum(purchase_amount), 2) AS total_revenue
FROM customers_behavior
GROUP BY subscription_status;
-- No. non_subscribers spend more and contributing in more revenue compared to subscriber.
-- The non-subscribers are more than subscribers. 


--Q6. Which 5 products have the highest percentage of purchases with discounts applied.

WITH CTE1 AS (
SELECT count(*) AS total_purchases
FROM customers_behavior
WHERE discount_applied = 'Yes' 
)
SELECT item_purchased, ROUND(100*sum(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)::NUMERIC/(SELECT total_purchases
												FROM CTE1), 2) 
												AS percent_purchases
FROM customers_behavior
GROUP BY item_purchased
ORDER BY percent_purchases DESC
LIMIT 5;
--or
SELECT item_purchased, ROUND(100*sum(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)::NUMERIC/(SELECT count(*) 
         FROM customers_behavior 
         WHERE discount_applied = 'Yes'), 2) AS percent_purchases
FROM customers_behavior
GROUP BY item_purchased
ORDER BY percent_purchases DESC
LIMIT 5;

--or
SELECT item_purchased, ROUND(100*(count(*)::NUMERIC/(SELECT count(*) 
         FROM customers_behavior 
         WHERE discount_applied = 'Yes')), 2) AS percent_purchases
FROM customers_behavior
WHERE discount_applied='Yes'
GROUP BY item_purchased
ORDER BY percent_purchases DESC
LIMIT 5;
--or
SELECT item_purchased, ROUND(100*count(*)::NUMERIC/(
					SELECT sum(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END) FROM customers_behavior), 2) 
				AS percent_purchases
FROM customers_behavior
WHERE discount_applied='Yes'
GROUP BY item_purchased
ORDER BY percent_purchases DESC
LIMIT 5;

-- The five products are Coat, Pant, Sweater, Jewelry and Hat.

--Q7. Segment customers into New, Returning, and Loyal based on their total number
--of previous purchases, and show the count of each segment.
WITH customer_type AS ( SELECT previous_purchases,
CASE WHEN previous_purchases <=1 THEN 'New' 
	WHEN previous_purchases <10 THEN 'Returning'
	ELSE 'Loyal' END AS customer_type
FROM customers_behavior
)
SELECT customer_type, count(*) AS num_customers
FROM customer_type
GROUP BY customer_type
ORDER BY num_customers DESC;


--Q8. What are the top 3 most purchased products within each category.
WITH total_purchased AS
(SELECT category,item_purchased, count(item_purchased) AS total_purchases
FROM customers_behavior
GROUP BY category, item_purchased)
SELECT * FROM (
	SELECT category, item_purchased, total_purchases,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY total_purchases DESC ) AS item_rank
	FROM total_purchased)
WHERE item_rank <=3;

--or 
WITH items_rank AS
( SELECT category, item_purchased, count(item_purchased) AS total_purchases,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(item_purchased) DESC) AS item_rank
FROM customers_behavior
GROUP BY category, item_purchased)
SELECT category, item_purchased, item_rank
FROM items_rank
WHERE item_rank<=3;


--Q.9 Are customers who are repreat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT count(customer_id) AS num_customers, subscription_status
FROM customers_behavior
WHERE previous_purchases>5
GROUP BY subscription_status;
-- No. repeat buyers (more than 5 previous purchases) are more likely to non subscriber
-- because most of customers have non-subscriber status

--Q10. What is revenue contribution of each age group.
SELECT age_group, sum(purchase_amount) AS total_revenue
FROM customers_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;
-- Young Adult contribute the most to the revenue.
